import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    "id": "1",
    "name": "Chingri Balachao Combo Offer",
    "nameBn": "চিংড়ি বালাচাও কম্বো অফার",
    "price": 900,
    "discount": 850,
    "description": "A traditional dried shrimp pickle (balachao) paired with a special spice mix – a combo pack for a complete Bengali meal experience. Made with sun-dried shrimp, fried onions, and aromatic spices.",
    "descriptionBn": "শুকনো চিংড়ি, ভাজা পেঁয়াজ ও মসলার মিশ্রণে তৈরি ঐতিহ্যবাহী চিংড়ি বালাচাও – সাথে বিশেষ মসলা মিশ্রণ। একেবারে ঘরোয়া স্বাদে ভাত বা রুটির সাথে পরিবেশন করুন।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": true,
    "weight": "500g (200g+300g)",
    "weightBn": "৫০০ গ্রাম (২০০+৩০০)",
    "deliveryCharge": 0
  },
  {
    "id": "2",
    "name": "Chingri Balachao with Beef Pickle Combo",
    "nameBn": "চিংড়ি বালাচাও গরুর মাংসের আচার কম্বো",
    "price": 850,
    "discount": 800,
    "description": "A delightful combo of traditional Chingri Balachao and spicy beef pickle – perfect for those who love both seafood and meat pickles.",
    "descriptionBn": "চিংড়ি বালাচাও ও ঝাল গরুর মাংসের আচারের দুর্দান্ত কম্বো – যারা সামুদ্রিক ও মাংসের আচার দুটোই পছন্দ করেন তাদের জন্য।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": true,
    "weight": "450g (250g+200g)",
    "weightBn": "৪৫০ গ্রাম (২৫০+২০০)",
    "deliveryCharge": 0
  },
  {
    "id": "3",
    "name": "Chingri Balachao 200g",
    "nameBn": "চিংড়ি বালাচাও ২০০ গ্রাম",
    "price": 350,
    "discount": 0,
    "description": "Classic Bengali dried shrimp pickle, packed with robust flavors of garlic, onion, and chili. A perfect side dish for rice or flatbread.",
    "descriptionBn": "রসুন, পেঁয়াজ ও মরিচের তীব্র স্বাদে ভরা ক্লাসিক চিংড়ি বালাচাও। ভাত বা রুটির সাথে অসাধারণ।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": false,
    "weight": "200g",
    "weightBn": "২০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "4",
    "name": "Chingri Balachao 300g",
    "nameBn": "চিংড়ি বালাচাও ৩০০ গ্রাম",
    "price": 450,
    "discount": 0,
    "description": "Larger pack of our signature Chingri Balachao – more shrimp, more spice, more flavor.",
    "descriptionBn": "বড় সাইজের চিংড়ি বালাচাও – বেশি চিংড়ি, বেশি মসলা, বেশি স্বাদ।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": false,
    "weight": "300g",
    "weightBn": "৩০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "5",
    "name": "Chingri Balachao 1kg",
    "nameBn": "চিংড়ি বালাচাও ১ কেজি",
    "price": 1750,
    "discount": 1600,
    "description": "Family-size jar of authentic Chingri Balachao – rich, savory, and perfect for large meals.",
    "descriptionBn": "পরিবারের জন্য বড় জারে খাঁটি চিংড়ি বালাচাও – সমৃদ্ধ, মুখরোচক ও বড় খাবারের জন্য আদর্শ।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 0
  },
  {
    "id": "6",
    "name": "Beef Pickle 250g",
    "nameBn": "গরুর মাংসের আচার ২৫০ গ্রাম",
    "price": 450,
    "discount": 390,
    "description": "Spicy and tangy beef pickle made with tender meat, mustard oil, and a secret blend of Bengali spices.",
    "descriptionBn": "নরম গরুর মাংস, সরিষার তেল ও গোপন মসলার মিশ্রণে তৈরি ঝাল-টক গরুর মাংসের আচার।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "7",
    "name": "Beef Pickle 500g",
    "nameBn": "গরুর মাংসের আচার ৫০০ গ্রাম",
    "price": 900,
    "discount": 850,
    "description": "Premium beef pickle in a larger pack – intense flavor, perfect for pickle lovers.",
    "descriptionBn": "বড় প্যাকেটে প্রিমিয়াম গরুর মাংসের আচার – তীব্র স্বাদ, আচারপ্রেমীদের জন্য।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": true,
    "weight": "500g",
    "weightBn": "৫০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "8",
    "name": "Beef Pickle 1kg",
    "nameBn": "গরুর মাংসের আচার ১ কেজি",
    "price": 1800,
    "discount": 1700,
    "description": "Economical family pack of authentic beef pickle, rich in spices and cooked to perfection.",
    "descriptionBn": "সাশ্রয়ী পরিবেশ-প্যাক খাঁটি গরুর মাংসের আচার – মসলায় পরিপূর্ণ ও নিখুঁত রান্না।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 0
  },
  {
    "id": "9",
    "name": "Sundarban Khalsha Flower Honey 250g",
    "nameBn": "সুন্দরবন খলিশা ফুলের মধু ২৫০ গ্রাম",
    "price": 400,
    "discount": 375,
    "description": "Pure honey collected from the rare Khalsha flowers of the Sundarbans – rich in antioxidants and naturally sweet.",
    "descriptionBn": "সুন্দরবনের বিরল খলিশা ফুল থেকে সংগৃহীত খাঁটি মধু – অ্যান্টিঅক্সিডেন্টে ভরপুর ও প্রাকৃতিক মিষ্টি।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "10",
    "name": "Sundarban Khalsha Flower Honey 500g",
    "nameBn": "সুন্দরবন খলিশা ফুলের মধু ৫০০ গ্রাম",
    "price": 800,
    "discount": 750,
    "description": "Larger jar of Sundarban Khalsha honey – unprocessed and full of floral aroma.",
    "descriptionBn": "বড় জারে সুন্দরবন খলিশা মধু – অপ্রক্রিয়াজাত ও ফুলের সুগন্ধে ভরা।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "500g",
    "weightBn": "৫০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "11",
    "name": "Sundarban Khalsha Flower Honey 1kg",
    "nameBn": "সুন্দরবন খলিশা ফুলের মধু ১ কেজি",
    "price": 1600,
    "discount": 1500,
    "description": "Premium 1kg pack of Sundarban honey – ideal for daily use and gifting.",
    "descriptionBn": "প্রিমিয়াম ১ কেজি সুন্দরবন মধু – দৈনন্দিন ব্যবহার ও উপহারের জন্য আদর্শ।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 0
  },
  {
    "id": "12",
    "name": "Black Cumin (Kalojira) Honey 250g",
    "nameBn": "কালোজিরা ফুলের মধু ২৫০ গ্রাম",
    "price": 350,
    "discount": 300,
    "description": "Rare black cumin flower honey – known for its medicinal properties and unique taste.",
    "descriptionBn": "বিরল কালোজিরা ফুলের মধু – ঔষধি গুণ ও অনন্য স্বাদের জন্য পরিচিত।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "13",
    "name": "Black Cumin (Kalojira) Honey 500g",
    "nameBn": "কালোজিরা ফুলের মধু ৫০০ গ্রাম",
    "price": 700,
    "discount": 600,
    "description": "Larger pack of black cumin honey – a powerhouse of nutrients and flavor.",
    "descriptionBn": "বড় প্যাকেট কালোজিরা মধু – পুষ্টি ও স্বাদের ভাণ্ডার।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "500g",
    "weightBn": "৫০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "14",
    "name": "Black Cumin (Kalojira) Honey 1kg",
    "nameBn": "কালোজিরা ফুলের মধু ১ কেজি",
    "price": 1400,
    "discount": 1200,
    "description": "Value-for-money 1kg pack of pure kalojira honey, perfect for families.",
    "descriptionBn": "সাশ্রয়ী ১ কেজি খাঁটি কালোজিরা মধু – পরিবারের জন্য উপযুক্ত।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 0
  },
  {
    "id": "15",
    "name": "Cream Honey 1kg",
    "nameBn": "ক্রিম হানি ১ কেজি",
    "price": 850,
    "discount": 700,
    "description": "Smooth, creamy honey with a buttery texture – a luxurious treat for honey lovers.",
    "descriptionBn": "মসৃণ, ক্রিমি টেক্সচারের মধু – মধুপ্রেমীদের জন্য এক বিলাসিতাময় উপহার।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 60
  },
  {
    "id": "16",
    "name": "Mustard Flower Honey 500g",
    "nameBn": "সরিষা ফুলের মধু ৫০০ গ্রাম",
    "price": 350,
    "discount": 325,
    "description": "Delicate and mild mustard flower honey, with a light floral taste.",
    "descriptionBn": "হালকা ফুলের স্বাদযুক্ত সরিষা ফুলের মধু – কোমল ও মিষ্টি।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "500g",
    "weightBn": "৫০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "17",
    "name": "Mustard Flower Honey 1kg",
    "nameBn": "সরিষা ফুলের মধু ১ কেজি",
    "price": 700,
    "discount": 650,
    "description": "Large pack of pure mustard honey, perfect for adding natural sweetness to drinks and dishes.",
    "descriptionBn": "বড় প্যাকেট খাঁটি সরিষা মধু – পানীয় ও খাবারে প্রাকৃতিক মিষ্টি যোগ করতে আদর্শ।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 0
  },
  {
    "id": "18",
    "name": "Mixed Honey 500g",
    "nameBn": "মিক্স মধু ৫০০ গ্রাম",
    "price": 500,
    "discount": 450,
    "description": "A harmonious blend of different floral honeys, offering a complex flavor profile.",
    "descriptionBn": "বিভিন্ন ফুলের মধুর সমন্বয়ে তৈরি মিক্স মধু – জটিল ও সমৃদ্ধ স্বাদ।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "500g",
    "weightBn": "৫০০ গ্রাম",
    "deliveryCharge": 0
  },
  {
    "id": "19",
    "name": "Mixed Honey 1kg",
    "nameBn": "মিক্স মধু ১ কেজি",
    "price": 1000,
    "discount": 900,
    "description": "Premium mixed honey in a large jar – a versatile sweetener for every kitchen.",
    "descriptionBn": "বড় জারে প্রিমিয়াম মিক্স মধু – প্রতিটি রান্নাঘরের জন্য বহুমুখী মিষ্টিকর।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 60
  },
  {
    "id": "20",
    "name": "Honey Nut 250g",
    "nameBn": "হানি নাট ২৫০ গ্রাম",
    "price": 350,
    "discount": 325,
    "description": "Crunchy nuts coated with pure honey – a healthy and energy-boosting snack.",
    "descriptionBn": "খাঁটি মধুতে লেপা ক্রাঞ্চি বাদাম – স্বাস্থ্যকর ও এনার্জি বাড়ানোর স্ন্যাক।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "21",
    "name": "Honey Nut 500g",
    "nameBn": "হানি নাট ৫০০ গ্রাম",
    "price": 700,
    "discount": 650,
    "description": "Larger pack of honey-coated mixed nuts – perfect for sharing or stocking up.",
    "descriptionBn": "বড় প্যাকেট মধু মিশ্রিত বাদাম – ভাগ করে খাওয়া বা মজুত রাখার জন্য।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "500g",
    "weightBn": "৫০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "22",
    "name": "Honey Nut 1kg",
    "nameBn": "হানি নাট ১ কেজি",
    "price": 1400,
    "discount": 1300,
    "description": "Family-sized jar of honey nuts – a delicious blend of health and taste.",
    "descriptionBn": "পরিবার-সাইজের জারে হানি নাট – স্বাস্থ্য ও স্বাদের সুন্দর সমন্বয়।",
    "image": null,
    "category": "Honey",
    "categoryBn": "মধু",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 60
  },
  {
    "id": "23",
    "name": "Ghee 250g",
    "nameBn": "ঘি ২৫০ গ্রাম",
    "price": 400,
    "discount": 375,
    "description": "Premium quality clarified butter (ghee) made from pure cow's milk – rich in aroma and golden in color.",
    "descriptionBn": "খাঁটি গরুর দুধে তৈরি প্রিমিয়াম ঘি – সুগন্ধি ও সোনালি রঙের।",
    "image": null,
    "category": "Ghee & Oils",
    "categoryBn": "ঘি ও তেল",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "24",
    "name": "Ghee 500g",
    "nameBn": "ঘি ৫০০ গ্রাম",
    "price": 800,
    "discount": 750,
    "description": "Larger pack of pure ghee – perfect for daily cooking and traditional sweets.",
    "descriptionBn": "বড় প্যাকেট খাঁটি ঘি – দৈনন্দিন রান্না ও ঐতিহ্যবাহী মিষ্টির জন্য।",
    "image": null,
    "category": "Ghee & Oils",
    "categoryBn": "ঘি ও তেল",
    "isNew": false,
    "isOffer": true,
    "weight": "500g",
    "weightBn": "৫০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "25",
    "name": "Ghee 1kg",
    "nameBn": "ঘি ১ কেজি",
    "price": 1600,
    "discount": 1500,
    "description": "Economical 1kg jar of ghee – high-quality clarified butter for every household.",
    "descriptionBn": "সাশ্রয়ী ১ কেজি জার ঘি – প্রতিটি পরিবারের জন্য উচ্চমানের ঘি।",
    "image": null,
    "category": "Ghee & Oils",
    "categoryBn": "ঘি ও তেল",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 0
  },
  {
    "id": "26",
    "name": "Pure Mustard Oil 1kg",
    "nameBn": "খাঁটি সরিষার তেল ১ কেজি",
    "price": 280,
    "discount": 260,
    "description": "Cold-pressed pure mustard oil – strong pungent flavor, ideal for cooking and pickling.",
    "descriptionBn": "কোল্ড-প্রেস খাঁটি সরিষার তেল – তীব্র গন্ধ, রান্না ও আচারের জন্য আদর্শ।",
    "image": null,
    "category": "Ghee & Oils",
    "categoryBn": "ঘি ও তেল",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 60
  },
  {
    "id": "27",
    "name": "Pure Mustard Oil 5kg",
    "nameBn": "খাঁটি সরিষার তেল ৫ কেজি",
    "price": 1400,
    "discount": 1300,
    "description": "Bulk pack of pure mustard oil – perfect for commercial use or large families.",
    "descriptionBn": "বাল্ক প্যাক খাঁটি সরিষার তেল – বাণিজ্যিক ব্যবহার বা বড় পরিবারের জন্য।",
    "image": null,
    "category": "Ghee & Oils",
    "categoryBn": "ঘি ও তেল",
    "isNew": false,
    "isOffer": true,
    "weight": "5kg",
    "weightBn": "৫ কেজি",
    "deliveryCharge": 60
  },
  {
    "id": "28",
    "name": "Pure Coconut Oil 250g",
    "nameBn": "খাঁটি নারিকেল তেল ২৫০ গ্রাম",
    "price": 375,
    "discount": 350,
    "description": "Cold-pressed virgin coconut oil – natural, light, and perfect for hair, skin, and cooking.",
    "descriptionBn": "কোল্ড-প্রেস ভার্জিন নারিকেল তেল – প্রাকৃতিক, হালকা, চুল, ত্বক ও রান্নার জন্য।",
    "image": null,
    "category": "Ghee & Oils",
    "categoryBn": "ঘি ও তেল",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "29",
    "name": "Pure Coconut Oil 500g",
    "nameBn": "খাঁটি নারিকেল তেল ৫০০ গ্রাম",
    "price": 750,
    "discount": 700,
    "description": "Large pack of pure coconut oil – multipurpose and full of natural goodness.",
    "descriptionBn": "বড় প্যাকেট খাঁটি নারিকেল তেল – বহুমুখী ও প্রাকৃতিক গুণে ভরপুর।",
    "image": null,
    "category": "Ghee & Oils",
    "categoryBn": "ঘি ও তেল",
    "isNew": false,
    "isOffer": true,
    "weight": "500g",
    "weightBn": "৫০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "30",
    "name": "Pure Coconut Oil 1kg",
    "nameBn": "খাঁটি নারিকেল তেল ১ কেজি",
    "price": 1500,
    "discount": 1400,
    "description": "Premium 1kg coconut oil – unrefined, chemical-free, and rich in medium-chain triglycerides.",
    "descriptionBn": "প্রিমিয়াম ১ কেজি নারিকেল তেল – অপরিশোধিত, কেমিক্যালমুক্ত ও MCT সমৃদ্ধ।",
    "image": null,
    "category": "Ghee & Oils",
    "categoryBn": "ঘি ও তেল",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 60
  },
  {
    "id": "31",
    "name": "Bombay Chili Spicy Pickle 250g",
    "nameBn": "বোম্বাই মরিচের ঝাল আচার ২৫০ গ্রাম",
    "price": 300,
    "discount": 0,
    "description": "Intensely spicy pickle made with Bombay chili peppers – a fiery delight for heat lovers.",
    "descriptionBn": "বোম্বাই মরিচে তৈরি তীব্র ঝাল আচার – মসলাপ্রেমীদের জন্য দারুণ।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": false,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "32",
    "name": "Tamarind-Boroi Mixed Pickle 250g",
    "nameBn": "তেঁতুল-বড়ই মিক্সড আচার ২৫০ গ্রাম",
    "price": 200,
    "discount": 0,
    "description": "Tangy and sweet pickle combining tamarind and Indian jujube (boroi) – a classic Bengali favorite.",
    "descriptionBn": "তেঁতুল ও বড়ইয়ের টক-মিষ্টি আচার – বাঙালির ক্লাসিক প্রিয়।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": false,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "33",
    "name": "Tamarind Sweet & Sour Pickle 250g",
    "nameBn": "তেঁতুলের টক-মিষ্টি আচার ২৫০ গ্রাম",
    "price": 200,
    "discount": 0,
    "description": "Sweet and sour tamarind pickle – a delightful blend of sweet, tangy, and spicy flavors.",
    "descriptionBn": "টক-মিষ্টি তেঁতুল আচার – মিষ্টি, টক ও ঝালের চমৎকার সমন্বয়।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": false,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "34",
    "name": "Mango Sweet & Sour Pickle 250g",
    "nameBn": "আমের টক-মিষ্টি আচার ২৫০ গ্রাম",
    "price": 200,
    "discount": 0,
    "description": "Traditional mango pickle with a perfect balance of sweet and sour – a summer staple.",
    "descriptionBn": "ঐতিহ্যবাহী আম আচার – টক-মিষ্টির নিখুঁত ভারসাম্য, গ্রীষ্মকালের অপরিহার্য।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": false,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "35",
    "name": "Garlic Pickle 250g",
    "nameBn": "দেশি রসুনের আচার ২৫০ গ্রাম",
    "price": 300,
    "discount": 0,
    "description": "Pungent and flavorful garlic pickle – a must-have for garlic lovers, made with traditional spices.",
    "descriptionBn": "রসুনের তীব্র স্বাদের আচার – রসুনপ্রেমীদের জন্য আবশ্যক, ঐতিহ্যবাহী মসলায় তৈরি।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": false,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "36",
    "name": "Spice Bomb Pickle 250g",
    "nameBn": "স্পাইস বোম্ব আচার ২৫০ গ্রাম",
    "price": 200,
    "discount": 0,
    "description": "A spicy explosion of mixed ingredients – a bold pickle for adventurous palates.",
    "descriptionBn": "নানা উপাদানের ঝাল মিশ্রণ – দুঃসাহসী স্বাদের জন্য বোল্ড আচার।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": false,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "37",
    "name": "Mango Oil Pickle 250g",
    "nameBn": "আম তেলের আচার ২৫০ গ্রাম",
    "price": 300,
    "discount": 0,
    "description": "Rich and aromatic mango pickle preserved in mustard oil – a traditional delicacy.",
    "descriptionBn": "সরিষার তেলে সংরক্ষিত সমৃদ্ধ ও সুগন্ধি আম আচার – একটি ঐতিহ্যবাহী খাবার।",
    "image": null,
    "category": "Pickles & Balachao",
    "categoryBn": "আচার ও বালাচাও",
    "isNew": false,
    "isOffer": false,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "38",
    "name": "Cumin Powder 250g",
    "nameBn": "জিরা গুঁড়া ২৫০ গ্রাম",
    "price": 400,
    "discount": 350,
    "description": "Freshly ground cumin powder – rich in aroma and essential for Bengali and Indian cuisine.",
    "descriptionBn": "তাজা গুঁড়ো করা জিরা – সুগন্ধি ও বাংলা-ভারতীয় রান্নার অপরিহার্য মসলা।",
    "image": null,
    "category": "Spices",
    "categoryBn": "মশলা",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "39",
    "name": "Dry Red Chili Powder (Deseeded) 250g",
    "nameBn": "বোটা ছাড়ানো শুকনা মরিচ গুঁড়া ২৫০ গ্রাম",
    "price": 250,
    "discount": 0,
    "description": "Premium quality dried red chili powder, deseeded for a balanced heat – ideal for curries.",
    "descriptionBn": "প্রিমিয়াম শুকনা মরিচ গুঁড়া, বোটা ছাড়ানো – তরকারির জন্য আদর্শ।",
    "image": null,
    "category": "Spices",
    "categoryBn": "মশলা",
    "isNew": false,
    "isOffer": false,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "40",
    "name": "Roasted Coriander Powder 250g",
    "nameBn": "রোস্টেড ধনিয়া গুঁড়া ২৫০ গ্রাম",
    "price": 200,
    "discount": 190,
    "description": "Roasted coriander seeds ground to a fine powder – adds a nutty, aromatic flavor to dishes.",
    "descriptionBn": "ভাজা ধনিয়া বীজের গুঁড়া – খাবারে বাদামি ও সুগন্ধি স্বাদ আনে।",
    "image": null,
    "category": "Spices",
    "categoryBn": "মশলা",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "41",
    "name": "Premium Turmeric Powder 250g",
    "nameBn": "প্রিমিয়াম হলুদ গুঁড়া ২৫০ গ্রাম",
    "price": 150,
    "discount": 140,
    "description": "High-quality turmeric powder with intense color and earthy flavor – a staple in every kitchen.",
    "descriptionBn": "উচ্চমানের হলুদ গুঁড়া – তীব্র রং ও মাটির স্বাদ, প্রতিটি রান্নাঘরের অপরিহার্য।",
    "image": null,
    "category": "Spices",
    "categoryBn": "মশলা",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "42",
    "name": "Shahi Mezban Spice Mix 100g",
    "nameBn": "শাহী মেজবানি গুঁড়া মশলা ১০০ গ্রাম",
    "price": 300,
    "discount": 0,
    "description": "Special spice blend for authentic Mezban-style dishes – aromatic and richly flavored.",
    "descriptionBn": "মেজবানি স্টাইলের খাবারের জন্য বিশেষ মসলা মিশ্রণ – সুগন্ধি ও সমৃদ্ধ স্বাদ।",
    "image": null,
    "category": "Spices",
    "categoryBn": "মশলা",
    "isNew": false,
    "isOffer": false,
    "weight": "100g",
    "weightBn": "১০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "43",
    "name": "Dry Red Chili Powder 250g",
    "nameBn": "শুকনা মরিচ গুঁড়া ২৫০ গ্রাম",
    "price": 250,
    "discount": 200,
    "description": "Classic dried red chili powder – provides the perfect level of heat for spicy dishes.",
    "descriptionBn": "ক্লাসিক শুকনা মরিচ গুঁড়া – ঝাল খাবারের জন্য উপযুক্ত মাত্রার তাপ।",
    "image": null,
    "category": "Spices",
    "categoryBn": "মশলা",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "44",
    "name": "Dried Malta (Orange) 100g",
    "nameBn": "মাল্টা ড্রাই ১০০ গ্রাম",
    "price": 360,
    "discount": 0,
    "description": "Sun-dried maltas (oranges) – a sweet and tangy dried fruit snack, rich in vitamin C.",
    "descriptionBn": "রোদে শুকানো মাল্টা – মিষ্টি-টক ড্রাই ফ্রুট স্ন্যাক, ভিটামিন সি সমৃদ্ধ।",
    "image": null,
    "category": "Dry Fruits & Seeds",
    "categoryBn": "শুকনো ফল ও বীজ",
    "isNew": false,
    "isOffer": false,
    "weight": "100g",
    "weightBn": "১০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "45",
    "name": "Dried Apple 100g",
    "nameBn": "অ্যাপল ড্রাই ১০০ গ্রাম",
    "price": 450,
    "discount": 0,
    "description": "Crispy dried apple slices – naturally sweet and a healthy alternative to sugary snacks.",
    "descriptionBn": "মচমচে ড্রাই অ্যাপল – প্রাকৃতিক মিষ্টি ও স্বাস্থ্যকর স্ন্যাক।",
    "image": null,
    "category": "Dry Fruits & Seeds",
    "categoryBn": "শুকনো ফল ও বীজ",
    "isNew": false,
    "isOffer": false,
    "weight": "100g",
    "weightBn": "১০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "46",
    "name": "Dried Mango 100g",
    "nameBn": "ম্যাঙ্গো ড্রাই ১০০ গ্রাম",
    "price": 350,
    "discount": 0,
    "description": "Sweet and tangy dried mango slices – a tropical delight bursting with flavor.",
    "descriptionBn": "মিষ্টি-টক ড্রাই ম্যাঙ্গো – স্বাদে ভরা ট্রপিক্যাল আনন্দ।",
    "image": null,
    "category": "Dry Fruits & Seeds",
    "categoryBn": "শুকনো ফল ও বীজ",
    "isNew": false,
    "isOffer": false,
    "weight": "100g",
    "weightBn": "১০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "47",
    "name": "Banana with Nuts 100g",
    "nameBn": "কলা ড্রাই উইথ বাদাম ১০০ গ্রাম",
    "price": 220,
    "discount": 0,
    "description": "Dried banana chips mixed with nuts – a crunchy and energizing snack.",
    "descriptionBn": "বাদাম মিশ্রিত ড্রাই কলা চিপস – ক্রাঞ্চি ও এনার্জি দেয়ার স্ন্যাক।",
    "image": null,
    "category": "Dry Fruits & Seeds",
    "categoryBn": "শুকনো ফল ও বীজ",
    "isNew": false,
    "isOffer": false,
    "weight": "100g",
    "weightBn": "১০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "48",
    "name": "Dried Jackfruit 100g",
    "nameBn": "কাঁঠাল ড্রাই ১০০ গ্রাম",
    "price": 350,
    "discount": 0,
    "description": "Dried jackfruit chips – a unique, mildly sweet snack with a satisfying crunch.",
    "descriptionBn": "ড্রাই কাঁঠাল চিপস – একটি অনন্য, হালকা মিষ্টি স্ন্যাক।",
    "image": null,
    "category": "Dry Fruits & Seeds",
    "categoryBn": "শুকনো ফল ও বীজ",
    "isNew": false,
    "isOffer": false,
    "weight": "100g",
    "weightBn": "১০০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "49",
    "name": "Cashew Nuts 250g",
    "nameBn": "কাজুবাদাম ২৫০ গ্রাম",
    "price": 500,
    "discount": 450,
    "description": "Premium whole cashew nuts – creamy and rich, perfect for snacking or cooking.",
    "descriptionBn": "প্রিমিয়াম পুরো কাজুবাদাম – ক্রিমি ও সমৃদ্ধ, স্ন্যাক বা রান্নার জন্য।",
    "image": null,
    "category": "Dry Fruits & Seeds",
    "categoryBn": "শুকনো ফল ও বীজ",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "50",
    "name": "Almonds 250g",
    "nameBn": "কাঠবাদাম ২৫০ গ্রাম",
    "price": 450,
    "discount": 425,
    "description": "High-quality almonds – nutrient-dense and versatile for both sweet and savory dishes.",
    "descriptionBn": "উচ্চমানের কাঠবাদাম – পুষ্টিসমৃদ্ধ, মিষ্টি ও নোনতা খাবার উভয়ে ব্যবহার্য।",
    "image": null,
    "category": "Dry Fruits & Seeds",
    "categoryBn": "শুকনো ফল ও বীজ",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "51",
    "name": "Chia Seeds 250g",
    "nameBn": "চিয়া সিড ২৫০ গ্রাম",
    "price": 180,
    "discount": 150,
    "description": "Superfood chia seeds – rich in omega-3, fiber, and antioxidants; perfect for smoothies and puddings.",
    "descriptionBn": "সুপারফুড চিয়া সিড – ওমেগা-৩, ফাইবার ও অ্যান্টিঅক্সিডেন্টসমৃদ্ধ; স্মুদি ও পুডিংয়ের জন্য আদর্শ।",
    "image": null,
    "category": "Dry Fruits & Seeds",
    "categoryBn": "শুকনো ফল ও বীজ",
    "isNew": false,
    "isOffer": true,
    "weight": "250g",
    "weightBn": "২৫০ গ্রাম",
    "deliveryCharge": 60
  },
  {
    "id": "52",
    "name": "Date Jaggery (Patali Gur) 1kg",
    "nameBn": "খেজুরের গুড় ১ কেজি",
    "price": 500,
    "discount": 450,
    "description": "Premium quality date jaggery (patali gur) from Jessore – naturally sweet and mineral-rich, a traditional winter delight.",
    "descriptionBn": "যশোরের প্রিমিয়াম খেজুরের পাটালি গুড় – প্রাকৃতিক মিষ্টি ও খনিজসমৃদ্ধ, শীতের ঐতিহ্যবাহী খাবার।",
    "image": null,
    "category": "Jaggery & Sweeteners",
    "categoryBn": "গুড় ও মিষ্টি",
    "isNew": false,
    "isOffer": true,
    "weight": "1kg",
    "weightBn": "১ কেজি",
    "deliveryCharge": 60
  }
];

export const CATEGORIES = [
  { "en": "All", "bn": "সবগুলো", "image": null },
  { "en": "Pickles & Balachao", "bn": "আচার ও বালাচাও", "image": null },
  { "en": "Honey", "bn": "মধু", "image": null },
  { "en": "Ghee & Oils", "bn": "ঘি ও তেল", "image": null },
  { "en": "Spices", "bn": "মশলা", "image": null },
  { "en": "Dry Fruits & Seeds", "bn": "শুকনো ফল ও বীজ", "image": null },
  { "en": "Jaggery & Sweeteners", "bn": "গুড় ও মিষ্টি", "image": null }
];

export const PRICING_CONFIG = {
  // Config: Set true to display discount/selling price first, then regular price. Set false for regular price first.
  showDiscountFirst: true,

  // Config: Set true to apply a strike-through line on the regular (original) price
  strikeThroughRegularPrice: true,

  // Helper to check if the product has a discount set and active
  hasDiscount: (product: any): boolean => {
    if (!product) return false;
    const hasOriginalPrice = product.originalPrice !== undefined && product.originalPrice !== null && Number(product.originalPrice) > Number(product.price);
    const hasDiscountPercent = product.discount !== undefined && product.discount !== null && Number(product.discount) > 0;
    return !!(hasOriginalPrice || hasDiscountPercent);
  },

  // Helper to retrieve the regular (original) price
  getRegularPrice: (product: any): number | null => {
    if (!product) return null;
    if (product.originalPrice !== undefined && product.originalPrice !== null && Number(product.originalPrice) > 0) {
      return Number(product.originalPrice);
    }
    if (product.discount !== undefined && product.discount !== null && Number(product.discount) > 0) {
      // Calculate original price based on discount percentage
      return Math.round(Number(product.price) / (1 - Number(product.discount) / 100));
    }
    return null;
  },

  // Helper to retrieve the discount/active selling price
  getDiscountPrice: (product: any): number => {
    if (!product) return 0;
    return Number(product.price);
  },

  // Helper to retrieve the discount percentage (either direct or calculated)
  getDiscountPercentage: (product: any): number | null => {
    if (!product) return null;
    if (product.discount !== undefined && product.discount !== null && Number(product.discount) > 0) {
      return Number(product.discount);
    }
    if (product.originalPrice !== undefined && product.originalPrice !== null && Number(product.originalPrice) > Number(product.price)) {
      return Math.round(((Number(product.originalPrice) - Number(product.price)) / Number(product.originalPrice)) * 100);
    }
    return null;
  }
};

export const DELIVERY_CONFIG = {
  enabled: true,                // Whether delivery charge is enabled by default
  chargeInside: 60,             // Default delivery charge inside Dhaka/City
  chargeOutside: 130,           // Default delivery charge outside Dhaka/City
  freeThreshold: 1000           // Free delivery threshold
};
